/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.ArrayList;
import javax.swing.JLabel;
import modelo.Modelo;
import org.jpl7.Term;

/**
 *
 * @author asmal
 */
public class VentanaJuego extends javax.swing.JFrame {
    private Term[][] matrizMadre;
    Modelo pModelo;
    int x;
    int y;
    /**
     * Creates new form VentanaJuego
     */
    public VentanaJuego(Modelo modelo) {
        pModelo = modelo;
        pModelo.Dibujar();
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        matrizMadre = pModelo.GetMatrizMadre();
        x = pModelo.GetX();
        y = pModelo.GetY();
        /*ArrayList<JLabel> labelArray;
        for (int i = 0;i!=x;i++) {
            for (int j = 0;j!=y;j++) {
                if(matrizMadre[i][j].equals(listaValores[1])) {
                    JLabel label = new JLabel();
                    label.setSize(50, 50);
                    labelArray.add(label);
                    
                }
                else {System.out.print(" ");}
            }
            System.out.print("\n");
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1100));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1100));
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1100));
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1100));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo5.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
